source: "../../../../lib/config/fileconf.go"
destination: "../../../../docs/pages/reference/deployment/config"
examples_directory: "./section_examples"

# Please alphabetize the section list by type name.
sections:
  - type: AccessGraph
  - type: Apps
  - type: Auth
  - type: Databases
  - type: DebugService
  - type: Discovery
  - type: Global
  - type: JamfService
  - type: Kube
  - type: Metrics
  - type: Okta
  - type: PluginService
  - type: Proxy
  - type: Relay
    introduction: |
      The Relay Service is available in Teleport v18.3.0 and later.

      Represents the `relay_service` section of the configuration file.
  - type: SSH
  - type: TracingService
  - type: WindowsDesktopService

camel_case_exceptions:
  - AWS
  - AlloyDB
  - CORS
  - DocumentDB
  - EKS
  - ElastiCache
  - GCP
  - GitHub
  - GitLab
  - HTTP
  - IAM
  - ID
  - IdP
  - MFA
  - MemoryDB
  - MySQL
  - OIDC
  - OpenSearch
  - RDS
  - SAML
  - SQL
  - SSO
  - TLS
  - TPM

title_word_replacements:
  - App: Application
  - Db: Database
  - Ssh: SSH
  - Teleport: Instance-wide settings
